### ISSUE TITLE
Endpoints not matching

### ISSUE THREAD

**Issue by timosmd** [onewayautomation/ogamma-sdk#4]
Hello,

I am currently trying to connect to two different OPC-UA Servers with your SDK and "Hello World" example.

For the first one it works totally fine and I can access and read all nodes.

With the second one I am encountering a connection problem where I receive the wrong endpoint from the server. Connecting to this particular server works fine with UaExpert (it somehow ignores the wrong returned endpoint-url).

This is the Code I am using:

```
#include <opcua/Connection.h>
#include <iostream>
#include <conio.h>

using namespace std;
using namespace OWA::OpcUa;
int main (int argc, char** argv)
{
  (void)argc;
  (void)argv;

  bool succeeded = false;
  {
        auto connection = Connection::create("opc.tcp://128.130.57.75:4840", true);
        if (connection->connect().get().isGood())
        {

             cout << "Connection established" << endl;

             NodeId nodeId("NS1|String|DISPLAY_CURRENT", 1);
             nodeId.setStringIdentifier("DISPLAY_CURRENT", 1);
      
             for (int i = 0; i < 100; i++) {
                 ReadRequest::Ptr readRequest(new ReadRequest(nodeId));
                 auto readResponse = connection->send(readRequest).get();
                 if (readResponse->isGood() && readResponse->results.size() == 1 && Utils::isGood(readResponse->results[0].statusCode))
                 {
                     cout << "READREQUEST # " << i << endl;
                     // We know that data type of the value is String, therefore convert it to string should succeed:
                     float currentValue = readResponse->results[0].value;
                     DateTime tstamp = readResponse->results[0].sourceTimestamp;
                     //string newValue = (currentValue == value1) ? value2 : value1;
                     cout << "DISPLAY_CURRENT: " << currentValue << endl;
                     const string abc;
                     cout << "TSTAMP: " << tstamp.toString() << endl;

                     succeeded = true;
                 }
             }

         _getch();
        }
  }

  OWA::OpcUa::Utils::closeSdk();
  if (!succeeded)
  {
    std::cout << "Reading value failed!" << std::endl;
    return -1;
  }
  else
  {
    return 0;
  }
}
```

Console Output:

![image](https://user-images.githubusercontent.com/56720702/81395301-a9fc7980-9123-11ea-9409-8a9a361af743.png)

Hope you can support me with this problem.

Thanks in advance!

**Comment by RavilN** [comment]
Hello,
The latest version of the SDK (internal, not available in this repository yet) handles this issue. It is caused by the server returning in GetEndpoints response local IP address which is not accessible from client side. 
Currently we don;t build the SDK with Visual Studio 2017, would the library built with Visual Studio 2019 work for you? If so, we can make latest version binaries available for you soon.

**Comment by timosmd** [comment]
Thanks for your quick response.

As I am using Visual Studio 2019 anyways it would be very nice if you could provide the binaries for me.

Thanks in advance!

**Comment by timosmd** [comment]
What do you think at which time you could provide the binaries? As I need to test it quite soon if it works, otherwise I need to have to look for alternate SDKs...

**Comment by RavilN** [comment]
Have upgraded to the latest version, please try to use it.

**Comment by timosmd** [comment]
Great! Thanks a lot!

Will try it..

**Comment by timosmd** [comment]
I compiled the repository now and tried to use it but couldn't make it working.

When compiling I encountered the problem that it didn't clone and compile botan when starting "install-opcuasdk-dependencies.cmd". So I did it manually afterwards everything else finished by calling "build-botan.ps1".

While the example "Hello World" seems to work fine, I am receiving an Error when using the code I posted earlier - even for the server which worked before.

It just terminates the program after the line "if (connection->connect().get().isGood())" with an exception with error code "0xC0000005: Access violation when reading at position 0x0000000000000050" and I can't find the reason why...

**Comment by timosmd** [comment]
Thanks a lot - it seems to work now.

To document for others users what I did differently to previous version:

- Start Powershell and allow execution of scripts with command "Set-ExecutionPolicy Unrestricted"
- Add "nmake"-folder from Visual Studio to environment variables path
- Also change path for vcvars64 in "build-botan.ps1"
- I had to call execution of "build-botan.ps1" manually after anything else downloaded and compiled as it didn't work with "install-opcuasdk-dependencies.cmd
- Use "OWA::OpcUa::Utils::initSdk();" before connection -> Already added in new version of "HelloWorld.cpp"
