### ISSUE TITLE
Timezone of Server-Timestamp

### ISSUE THREAD

**Issue by timosmd** [onewayautomation/ogamma-sdk#5]
Is there a way to change the timezone in which the server- & source-timestamp is returned from the nodes? The timestamp I receive from the OpcUa-Server differs to the one that is shown in UaExpert by 2 hours.

Thanks in advance!

**Comment by RavilN** [comment]
Hi,
OPC UA Servers return timestamps always in the UTC time zone. It is up to the OPC UA clients to translate it into local time. 
If you want to display timestamps, you can use variations of DateTime::toString method and control, what timezone to use:
	DateTime dt(true);

	// default: UTC time
	std::cout << "Default time zone (UTC):	" << dt.toString() << std::endl;

	// Modified delimiters, postfix, precision:
	std::cout << "Default time zone (UTC):	" << dt.toString(false, false, ' ', '\0', DateTime::Precision::Milliseconds) << std::endl;
	std::cout << "Default time zone (UTC):	" << dt.toString(false, true, 'T', 'Z', DateTime::Precision::Microseconds) << std::endl;
	std::cout << "Default time zone (UTC):	" << dt.toString(false, false, 'T', '\0', DateTime::Precision::Microseconds) << std::endl;

	// This machine's local time zone:
	std::cout << "Local time zone:          " << dt.toString(true) << std::endl;

	// Manual translation to any other time zone:
	std::chrono::seconds timeDiff(60 * 60 * 2);
	std::cout << "2 hours behind UTC:       " << (dt - timeDiff).toString() << std::endl;

Output for this code is:

Default time zone (UTC):        2020-06-23 15:20:15.267.318.0
Default time zone (UTC):        2020-06-23 15:20:15.267
Default time zone (UTC):        2020-06-23T15:20:15.267.318Z
Default time zone (UTC):        2020-06-23T15:20:15.267318
Local time zone:          2020-06-23 09:20:15.267.318.0
2 hours behind UTC:       2020-06-23 13:20:15.267.318.0

**Comment by timosmd** [comment]
Thanks for your answer! Thought there might be an integrated function but your solution should suit my needs as well :)

**Comment by timosmd** [comment]
Issue solved
