### ISSUE TITLE
Monitoring Nodes

### ISSUE THREAD

**Issue by timosmd** [onewayautomation/ogamma-sdk#6]
Hello,

currently I am reading all of my Nodes (around 40) in a while-loop and appending them to a buffer when read. 

But I experienced a decreased sample rate when adding nodes to my reading-loop. 
e.g.: 1 Node to read -> Sample rate = 200Hz (adding 200 values to my buffer per second).
       4 Nodes to read -> Sample rate = 40Hz

Also I thought about just reading/storing node-values as soon as the value changed. 

Looking through your code I think this should be possible, but I couldn't manage to make it run - Could you maybe provide me a short example of how to use the notification on value change?

Thanks in advance!

**Comment by timosmd** [comment]
I think the bottleneck here is the time for the ReadRequest & Response. Is there a way to create one Request & Response for all Nodes at once?

**Comment by RavilN** [comment]
Hi,
Yes, you got it correctly - read request can have more than one element in the nodesToRead member.
In fact, request and response classes have the same members as parameters of corresponding services defined in Part 4 of OPC UA Specs.
The sample project has been modified to read more than one node, and an example is also added to create a subscription and monitored items.
Also added an example on how to browse, synchronously as well as asynchronously.
Regards, Ravil

**Comment by timosmd** [comment]
Thanks a lot! I will have a look 👍

**Comment by timosmd** [comment]
Issue solved
